import os
import csv
import json
from pathlib import Path


# =========================
# CONFIGURATION
# =========================

INPUT_DIR = r"" # Path to dataset directory containing images and metadata
RAW_PRED_PATH = Path("outputs/predictions_raw.json")
CSV_OUTPUT_PATH = Path("outputs/predictions.csv")


# =========================
# UTILITIES
# =========================

def recover_original_name(file_stem):
    """
    Recover original image name and crop side indicator.

    The inference pipeline processes images split into left/right crops.
    This function restores the original image identity.

    Examples
    --------
    "image_001_L" -> ("image_001", "L")
    "image_001_R" -> ("image_001", "R")

    Parameters
    ----------
    file_stem : str
        Filename without extension.

    Returns
    -------
    tuple
        (original_name, crop_side)
    """
    if file_stem.endswith("_L"):
        return file_stem[:-2], "L"

    if file_stem.endswith("_R"):
        return file_stem[:-2], "R"

    return file_stem, "FULL"


def find_metadata_file(folder, original_name):
    """
    Locate metadata file associated with an image.

    The dataset structure assumes:
    - image file
    - metadata file with same stem
    - optional extra file (ignored)

    Parameters
    ----------
    folder : str or Path
        Dataset directory containing images and metadata.

    original_name : str
        Base name of the image without crop suffix.

    Returns
    -------
    Path or None
        Path to metadata file if found, otherwise None.
    """

    folder = Path(folder)

    for f in folder.iterdir():

        if f.stem != original_name:
            continue

        if f.suffix.lower() in VALID_EXT:
            continue

        if f.suffix.lower() == ".txt":
            continue

        return f

    return None


def read_metadata(path):
    """
    Read metadata file content as raw text.

    Parameters
    ----------
    path : Path or None
        Path to metadata file.

    Returns
    -------
    str
        File content or empty string if not found.
    """

    if path is None:
        return ""

    try:
        return Path(path).read_text(encoding="utf-8")
    except Exception:
        return ""


# =========================
# CSV EXPORT PIPELINE
# =========================

def export_to_csv():
    """
    Converts raw inference JSON into a structured CSV file.

    This function:
    - Loads predictions generated by inference.py
    - Reconstructs original image identity (L/R crops)
    - Associates metadata files with each image
    - Flattens detection results (bbox + confidence)
    - Saves final dataset into a CSV format

    CSV columns:
        image_file, original_image, crop_side,
        metadata_file, metadata_content,
        class, confidence,
        bbox_xmin, bbox_ymin, bbox_xmax, bbox_ymax

    Returns
    -------
    None
    """

    with open(RAW_PRED_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    os.makedirs(CSV_OUTPUT_PATH.parent, exist_ok=True)

    with open(CSV_OUTPUT_PATH, "w", newline="", encoding="utf-8") as csv_file:

        writer = csv.writer(csv_file)

        # Header
        writer.writerow([
            "image_file",
            "original_image",
            "crop_side",
            "metadata_file",
            "metadata_content",
            "class",
            "confidence",
            "bbox_xmin",
            "bbox_ymin",
            "bbox_xmax",
            "bbox_ymax",
        ])

        for item in data:

            image_file = item["image"]

            stem = Path(image_file).stem
            original, side = recover_original_name(stem)

            metadata_path = find_metadata_file(INPUT_DIR, original)
            metadata_content = read_metadata(metadata_path)

            for pred in item["predictions"]:

                bbox = pred["bbox"]

                writer.writerow([
                    image_file,
                    original,
                    side,
                    metadata_path.name if metadata_path else "",
                    metadata_content,
                    pred["class"],
                    pred["confidence"],
                    bbox["xmin"],
                    bbox["ymin"],
                    bbox["xmax"],
                    bbox["ymax"],
                ])

    print(f"CSV generated at: {CSV_OUTPUT_PATH}")


# =========================
# ENTRY POINT
# =========================

if __name__ == "__main__":
    export_to_csv()
